version: 2
jobs:
  deploy:
    docker:
      - image: python:2.7
      - image: node:12
    working_directory: ~/repo
    steps:
      - run:
          name: Install npm package
          command: npm install
      - run:
          name: Make build directory
          command: npm run build
      - run:
          name: Install awscli
          command: pip install awscli
      - run:
          name: Deploy to S3
          command: aws s3 sync ./build s3://shoes-store-ui --delete
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
